# ML Pipeline Preparation
Follow the instructions below to help you create your ML pipeline.
### 1. Import libraries and load data from database.
- Import Python libraries
- Load dataset from database with [`read_sql_table`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_table.html)
- Define feature and target variables X and Y

In [1]:
# import libraries
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

import nltk

nltk.download(['punkt','wordnet','averaged_perceptron_tagger','stopwords'])

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kshitij\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\kshitij\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\kshitij\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kshitij\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
# load data from database
engine = create_engine("postgresql+psycopg2://postgres:qweasdzxc@localhost:1026/ds_response")
df = pd.read_sql('SELECT * FROM msg_categories',engine)

In [3]:
df.reset_index(drop=True, inplace=True)

In [4]:
target_cols = df.drop(columns = ['id','message','original','genre','genre'])
for col in target_cols.columns:
    print(df[col].unique(),end="")

[1 0 2][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1]

In [5]:
target_cols.related.replace(2,1,inplace=True)

In [6]:
target_cols.related.unique()

array([1, 0], dtype=int64)

In [7]:
df.head(2)

id                                            message  \
0   2  Weather update - a cold front from Cuba that c...   
1   7            Is the Hurricane over or is it not over   

                                            original   genre  related  \
0  Un front froid se retrouve sur Cuba ce matin. ...  direct        1   
1                 Cyclone nan fini osinon li pa fini  direct        1   

   request  offer  aid_related  medical_help  medical_products  ...  \
0        0      0            0             0                 0  ...   
1        0      0            1             0                 0  ...   

   aid_centers  other_infrastructure  weather_related  floods  storm  fire  \
0            0                     0                0       0      0     0   
1            0                     0                1       0      1     0   

   earthquake  cold  other_weather  direct_report  
0           0     0              0              0  
1           0     0              0              0  

[2 rows x 40 columns]

In [8]:
X = df.message.values
y = target_cols.values

In [9]:
print(X.shape,y.shape)

(26216,) (26216, 36)


### 2. Write a tokenization function to process your text data

In [10]:
def tokenize(text):
    
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")
    lemmatizer = WordNetLemmatizer()
    
    clean_tokens = [lemmatizer.lemmatize(word).lower().strip() for word in tokens if word not in stop_words]
    
    return clean_tokens

### 3. Build a machine learning pipeline
This machine pipeline should take in the `message` column as input and output classification results on the other 36 categories in the dataset. You may find the [MultiOutputClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputClassifier.html) helpful for predicting multiple target variables.

In [12]:
pipeline = Pipeline([
    ('vect', CountVectorizer(tokenizer = tokenize)),
    ('tfidf', TfidfTransformer()),
    ('clf', MultiOutputClassifier(RandomForestClassifier()))
])

### 4. Train pipeline
- Split data into train and test sets
- Train pipeline

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.2, random_state=42)

In [14]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vect',
                 CountVectorizer(tokenizer=<function tokenize at 0x00000294EC35CEE8>)),
                ('tfidf', TfidfTransformer()),
                ('clf',
                 MultiOutputClassifier(estimator=RandomForestClassifier()))])

### 5. Test your model
Report the f1 score, precision and recall for each output category of the dataset. You can do this by iterating through the columns and calling sklearn's `classification_report` on each.

In [15]:
y_pred = pipeline.predict(X_test)

In [17]:
target_names = [col for col in df.columns if col not in ['id', 'message', 'original', 'genre']]
len(target_names)

36

In [18]:
print(classification_report(y_test, y_pred, target_names=target_names))

                        precision    recall  f1-score   support

               related       0.83      0.96      0.89      4039
               request       0.85      0.47      0.61       917
                 offer       0.00      0.00      0.00        24
           aid_related       0.77      0.67      0.71      2169
          medical_help       0.62      0.05      0.09       410
      medical_products       0.78      0.08      0.15       259
     search_and_rescue       1.00      0.03      0.05       151
              security       0.00      0.00      0.00        85
              military       0.69      0.06      0.11       150
           child_alone       0.00      0.00      0.00         0
                 water       0.86      0.29      0.44       331
                  food       0.84      0.47      0.60       602
               shelter       0.84      0.36      0.50       448
              clothing       0.80      0.05      0.10        75
                 money       1.00      

C:\Users\kshitij\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kshitij\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kshitij\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kshitij\anaconda3\lib\site-packages\sklearn\metr

### 6. Improve your model
Use grid search to find better parameters. 

In [21]:
pipeline.get_params()

{'memory': None,
 'steps': [('vect',
   CountVectorizer(tokenizer=<function tokenize at 0x00000294EC35CEE8>)),
  ('tfidf', TfidfTransformer()),
  ('clf', MultiOutputClassifier(estimator=RandomForestClassifier()))],
 'verbose': False,
 'vect': CountVectorizer(tokenizer=<function tokenize at 0x00000294EC35CEE8>),
 'tfidf': TfidfTransformer(),
 'clf': MultiOutputClassifier(estimator=RandomForestClassifier()),
 'vect__analyzer': 'word',
 'vect__binary': False,
 'vect__decode_error': 'strict',
 'vect__dtype': numpy.int64,
 'vect__encoding': 'utf-8',
 'vect__input': 'content',
 'vect__lowercase': True,
 'vect__max_df': 1.0,
 'vect__max_features': None,
 'vect__min_df': 1,
 'vect__ngram_range': (1, 1),
 'vect__preprocessor': None,
 'vect__stop_words': None,
 'vect__strip_accents': None,
 'vect__token_pattern': '(?u)\\b\\w\\w+\\b',
 'vect__tokenizer': <function __main__.tokenize(text)>,
 'vect__vocabulary': None,
 'tfidf__norm': 'l2',
 'tfidf__smooth_idf': True,
 'tfidf__sublinear_tf': False,


In [22]:
# import libraries
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

import nltk

nltk.download(['punkt','wordnet','averaged_perceptron_tagger','stopwords'])

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

def load_data():
    
    #create an engine and extract data from sql
    
    engine = create_engine("postgresql+psycopg2://postgres:qweasdzxc@localhost:1026/ds_response")
    df = pd.read_sql('SELECT * FROM msg_categories',engine)
    
    #reset index
    df.reset_index(drop=True, inplace=True)
    
    #preparing data
    target_cols = df.drop(columns = ['id','message','original','genre','genre'])
    for col in target_cols.columns:
        print(df[col].unique(),end="")
    target_cols.related.replace(2,1,inplace=True)
    print(target_cols.related.unique())
    
    #Making X and y variables
    X = df.message.values
    y = target_cols.values
    
    return X,y,df

def tokenize(text):
    
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")
    lemmatizer = WordNetLemmatizer()
    
    clean_tokens = [lemmatizer.lemmatize(word).lower().strip() for word in tokens if word not in stop_words]
    
    return clean_tokens

def build_model():
    pipeline = Pipeline([
        ('vect', CountVectorizer(tokenizer = tokenize)),
        ('tfidf', TfidfTransformer()),
        ('clf', MultiOutputClassifier(KNeighborsClassifier()))
    ])
    
        #set gridsearch parameters 
    parameters = {
        
        'vect__max_df': (.75, 1.0),
        'tfidf__use_idf': (True,False)
    }
    cv = GridSearchCV(pipeline, param_grid=parameters, n_jobs=-1)
    return cv
    
def display_results(df,y_test, y_pred):
    
    target_names = [col for col in df.columns if col not in ['id', 'message', 'original', 'genre']]
    print(classification_report(y_test, y_pred, target_names=target_names))
    
def main():
    X, y, df = load_data()
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    
    model = build_model()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    display_results(df,y_test, y_pred)

main()

[nltk_data] <urlopen error [Errno 11001] getaddrinfo failed>


[1 0 2][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][0 1][1 0]


exception calling callback for <Future at 0x294b0553e88 state=finished raised BrokenProcessPool>
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\kshitij\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\kshitij\anaconda3\lib\multiprocessing\queues.py", line 113, in get
    return _ForkingPickler.loads(res)
AttributeError: 'WordListCorpusReader' object has no attribute '_unload'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kshitij\anaconda3\lib\site-packages\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "C:\Users\kshitij\anaconda3\lib\site-packages\joblib\parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\kshitij\anaconda3\lib\site-packa

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

### 7. Test your model
Show the accuracy, precision, and recall of the tuned model.  

Since this project focuses on code quality, process, and  pipelines, there is no minimum performance metric needed to pass. However, make sure to fine tune your models for accuracy, precision and recall to make your project stand out - especially for your portfolio!

### 8. Try improving your model further. Here are a few ideas:
* try other machine learning algorithms
* add other features besides the TF-IDF

### 9. Export your model as a pickle file

### 10. Use this notebook to complete `train.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database and export a model based on a new dataset specified by the user.